### ISSUE TITLE
Archive the project

### ISSUE THREAD

**Issue by pdorschner** [SAP/gorfc#34]
I was hitting an error and searching through the issues and saw that all issues are closed due sunset of the project.

Is this project dead? If it is so, then please archive the project to make this clear, so no one sets on this project anymore ...

**Comment by guettli** [comment]
@bsrdjan do you have any updates to the state of the project?

**Comment by SimonWaldherr** [comment]
I use it in production without any problems

**Comment by bsrdjan** [comment]
Hello @guettli, I am not any more involved in gorfc project but @auhlig or @databus23 might have more info on status

**Comment by auhlig** [comment]
Hi all and sorry for the late reply. I missed this in my inbox.

This go RFC binding is being used in production and we continue to actively maintain it.
Otherwise, we'd certainly reflect any other state in the documentation.

The project was briefly marked for sunset during a SAP-internal change of ownership.
We cleaned up and might have closed some no longer relevant issues. 
If we accidentally closed something that's still relevant for you, then please re-open it and feel encouraged to contribute to this project.
